src/AppBundle/Entity/Institution.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Institution
 *
 * @ORM\Table(name="institution")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\InstitutionRepository")
 * @Vich\Uploadable
 */
class Institution
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Review", mappedBy="institution")
     */
    private $reviews;

    /**
     * @ORM\Column(name="avatar", type="text", nullable=true)
     */
    private $avatar;

    /**
     * @var string
     * @ORM\Column(name="name", type="string", nullable=true, unique=true)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="avatar_file", fileNameProperty="avatar")
     *
     * @var File
     */
    private $avatarFile;
    
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Image", mappedBy="institution")
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Category", inversedBy="institutions")
     */
    private $category;

    /**
     * @var float
     * @ORM\Column(name="overral_score",type="float")
     */
    private $overral_score = 0;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="institutions")
     */
    private $user;


    /**
     * @var bool
     * @ORM\Column(name="is_active", type="boolean", nullable=true)
     */
    protected $isActive;


    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getNumberOfImages(){
        return count($this->getImages());
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Institution
     */
    public function setAvatarFile(File $image = null)
    {
        $this->avatarFile = $image;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getAvatarFile()
    {
        return $this->avatarFile;
    }
    /**
     * @param string $reviews
     * @return Institution
     */
    public function setReviews($reviews)
    {
        $this->reviews = $reviews;
        return $this;
    }

    /**
     * @return string
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    /**
     * @param boolean $isActive
     * @return Institution
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Add review
     *
     * @param \AppBundle\Entity\Review $review
     *
     * @return Institution
     */
    public function addReview(\AppBundle\Entity\Review $review)
    {
        $this->reviews[] = $review;

        return $this;
    }

    /**
     * Remove review
     *
     * @param \AppBundle\Entity\Review $review
     */
    public function removeReview(\AppBundle\Entity\Review $review)
    {
        $this->reviews->removeElement($review);
    }

    /**
     * Add image
     *
     * @param \AppBundle\Entity\Image $image
     *
     * @return Institution
     */
    public function addImage(\AppBundle\Entity\Image $image)
    {
        $this->images[] = $image;

        return $this;
    }

    /**
     * Remove image
     *
     * @param \AppBundle\Entity\Image $image
     */
    public function removeImage(\AppBundle\Entity\Image $image)
    {
        $this->images->removeElement($image);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Set category
     *
     * @param \AppBundle\Entity\Category $category
     *
     * @return Institution
     */
    public function setCategory(\AppBundle\Entity\Category $category = null)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return \AppBundle\Entity\Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Institution
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return Institution
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Institution
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Institution
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
    
    /**
     * Set overralScore
     *
     * @param float $overralScore
     *
     * @return Institution
     */
    public function setOverralScore($overralScore)
    {
        $this->overral_score = $overralScore;

        return $this;
    }

    /**
     * Get overralScore
     *
     * @return float
     */
    public function getOverralScore()
    {
        return $this->overral_score;
    }

    /**
     * @return int
     */
    public function getNumberOfReviews(){
        $reviews = $this->getReviews();
       return count($reviews);
    }
}

src/AppBundle/Controller/BasicController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Form\searchInstitutionType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class BasicController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        $institutions = $this->getDoctrine()
            ->getRepository('AppBundle:Institution')
            ->findAll();

        $categories = $this->getDoctrine()
            ->getRepository('AppBundle:Category')
            ->findAll();

        return $this->render('@App/Basic/index.html.twig', [
            'institutions' => $institutions,
            'categories' => $categories,
        ]);
    }

//    /**
//     * @Route("/{category_name}", name="show_category")
//     * @param string $category_name
//     * @return \Symfony\Component\HttpFoundation\Response
//     * @internal param Request $request
//     */
//    public function showCategoryAction(string $category_name)
//    {
//        $category = $this->getDoctrine()
//            ->getRepository('AppBundle:Category')
//            ->findByName($category_name);
//        $isCategory = false;
//        return $this->render('@App/Basic/index.html.twig', [
//            'isCategory'=>$isCategory,
//            'institutions' => $institutions,
//            'categories' => $categories
//        ]);
//    }


}

src/AppBundle/Resources/views/Basic/index.html.twig
{% extends "@App/menu.html.twig" %}

{% block title %}AppBundle:Basic:index{% endblock %}
{% block body %}
    <div class="row">
        <div class="container ">
            <ul class="nav nav-tabs">
                <li><a href="{{ path('homepage') }}">Главная</a></li>
                {% if not is_granted('ROLE_USER') %}
                    <li><a href="{{ path('fos_user_registration_register') }}">Регистрация</a></li>
                    <li><a href="{{ path('fos_user_security_login') }}">Авторизация</a></li>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                    <li><a href="{{ path('sonata_admin_dashboard') }}" id="admin_panel">Админская панель</a></li>
                {% endif %}
                <li>
                    <form action="{{ path('search_institution') }}">
                        <p><input type="search" name="word" placeholder="Поиск по заведения">
                            <input type="submit" value="Найти"></p>
                    </form>
                </li>
                {% if is_granted('ROLE_USER') %}
                    <li><a href="{{ path('add_place') }}">Добавить новое место</a></li>
                    <li><a href="{{ path('fos_user_security_logout') }}">Выйти</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

    {% block content %}
        <div class="container">
            <div class="row">

                <h1>Главная страница</h1>
                {% for flashMessage in app.session.flashbag.get('greeting') %}
                    <div class="col-lg-offset-3 col-lg-3 col-lg-offset-3">{{ flashMessage }}</div>
                    {% if is_granted('ROLE_USER') %}
                        <p>Но вы можете добавить это место</p>
                        <a href="{{ path('add_place') }}"> Перейдя по ссылке </a>
                    {% endif %}
                {% endfor %}
                <div class="col-lg-12">
                    <h2>Выбери Категорию</h2>

                    {% for category in categories %}
                        <a href=""> {{ category.name }}</a>
                    {% endfor %}
                </div>

                {% for institution in institutions %}
                    {% if institution.isActive == true %}
                        <div class="col-lg-3">
                            <a href="{{ path('app_institution_showinstitution', {'id': institution.id }) }}">
                                <img class="img-thumbnail" width="200" height="200"
                                     src="{{ vich_uploader_asset(institution, 'avatarFile') }}">
                            </a>
                            <a href="{{ path('app_institution_showinstitution', {'id': institution.id }) }}">
                                <p class="text-danger">{{ institution.name }}</p>
                            </a>
                            <h4> Средний рейтинг: {{ institution.overralScore }}
                                Комментарии: {{ institution.numberOfReviews }}</h4>
                            <p class="text-info">Фотографий:{{ institution.numberOfImages }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endblock %}

{% endblock %}